### ISSUE TITLE
Add GetTenantByNameAsync method

### ISSUE THREAD

**Issue by jamesbroome** [marain-dotnet/Marain.Tenancy#111]
Would like the ability to retrieve a tenant by its name (instead of ID) to support scenarios where we want to validate that a tenant name isn't already in use. 

In SaaS applications keeping tenant names unique is important for scenarios where we want to support things like custom DNS/sub-domains/AADB2B tenants etc etc.

**Comment by mwadams** [comment]
I don't think that unique names for tenants is the right way to go about that.

You can use a "well known" ID for a tenant, and that guarantees uniqueness. Using e.g. a domain name for that would be one very effective approach.

Otherwise, you end up with multiple "unique" IDs.

We had a very long discussion about this before, and I believe that we have ADRs on the subject.

**Comment by mwadams** [comment]
To summarise

1) There is exactly 1 unique ID for a tenant
2) The name is a convenient "human readable" label for a tenant, not an ID
3) Features like "associating domain names with the tenant" are orthogonal to the tenant ID itself. Not least because domain name associations are almost invariably 1:many (e.g. `.com`, `.co.uk`, `.net`, `.io`)
